#!/bin/bash

echo -n "Restarting network service"
service networking restart

echo "Setting up ip address"
ifconfig eth0 up 172.16.60.1/24

echo "Setting up default route (Cisco Router)"
route add default gw 172.16.60.254

echo "Setting up route to VLAN 60"
route add -net 172.16.61.0/24 gw 172.16.60.254

echo "Setting up DNS"
printf "search netlab.fe.up.pt\nnameserver 172.16.1.1\nnameserver 172.16.2.1\n" > /etc/resolv.conf 
